services:
  - type: web
    name: rhys-harmer-election-statement
    runtime: static
    buildCommand: echo "Static files ready"
    staticPublishPath: ./election-statements/rhys-harmer
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex, nofollow
  - type: web
    name: glen-hart-election-statement
    runtime: static
    buildCommand: echo "Static files ready"
    staticPublishPath: ./election-statements/glen-hart
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex, nofollow
